unit TestFD.Compiler.Lexer;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, FD.Compiler.Lexer, FD.Compiler.Environment,
  TestFD.TestBase;

type
  // Test methods for class TPascalPreprocessor

  TestTLexer = class(TestFDBase)
  protected
    FLexer: TLexer;
  end;

implementation

end.


