unit TestFD.TestBase;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, System.SysUtils, System.Classes, System.IOUtils;

type
  // Test methods for class TPascalPreprocessor

  TestFDBase = class(TTestCase)
  protected
    class var
      FTempTestDir: String;

    class procedure Initialize;
  protected
    FTestDir: String;

    procedure SetupEnv(CaseID: String); virtual;
  end;

const
  SORUCE_CASES_DIR = 'E:\OneDrive\FireDev\Tests\Cases\';  // CHANGE THIS

implementation

{$IFDEF MSWINDOWS}
uses
  Winapi.Windows, ShellApi, SHFolder;
{$ENDIF}

{ TestFDBase }

class procedure TestFDBase.Initialize;
const
  FIREDEV_SUBDIR = 'FireDevTest';
begin
  {$IFDEF MSWINDOWS}
    SetLength(FTempTestDir, MAX_PATH + 1);

    if Succeeded(SHGetFolderPath(0, CSIDL_APPDATA, 0, SHGFP_TYPE_CURRENT, PChar(FTempTestDir))) then
    begin
      FTempTestDir := PChar(FTempTestDir); // copiar até o caracter #0
      FTempTestDir :=  IncludeTrailingPathDelimiter(FTempTestDir) + FIREDEV_SUBDIR + PathDelim;
    end else
      FTempTestDir := IncludeTrailingPathDelimiter(TPath.GetDocumentsPath()) + FIREDEV_SUBDIR + PathDelim;
  {$ELSE}
    FTempTestDir := IncludeTrailingPathDelimiter(TPath.GetDocumentsPath()) + FIREDEV_SUBDIR + PathDelim;
  {$ENDIF}
end;

procedure TestFDBase.SetupEnv(CaseID: String);
var
  SourceCaseDir: String;
begin
  CaseID := StringReplace(CaseID, '/', PathDelim, [rfReplaceAll]);
  CaseID := StringReplace(CaseID, '\', PathDelim, [rfReplaceAll]);

  FTestDir := TestFDBase.FTempTestDir;

  if TDirectory.Exists(ExcludeTrailingPathDelimiter(FTestDir)) then
    TDirectory.Delete(ExcludeTrailingPathDelimiter(FTestDir), True);

  SourceCaseDir := IncludeTrailingPathDelimiter(IncludeTrailingPathDelimiter(SORUCE_CASES_DIR) + CaseID);

  Assert(TDirectory.Exists(ExcludeTrailingPathDelimiter(SourceCaseDir)), 'TestCase "'+ CaseID +'" not found at "' + SourceCaseDir + '"');
  TDirectory.Copy(ExcludeTrailingPathDelimiter(SourceCaseDir), ExcludeTrailingPathDelimiter(FTestDir));
end;

initialization
  TestFDBase.Initialize();

end.


